version: '3.2'
services:
  app1:
    build: ./app
    expose:
      - '3000' # Expose ports without publishing them to the host machine
    environment:
      MESSAGE: 'First instance'
  app2:
    build: ./app
    expose:
      - '3000' # Expose ports without publishing them to the host machine
    environment:
      MESSAGE: 'Second instance'
  web:
    build: ./nginx
    ports:
      - '88:80'
    links:
      - app1
      - app2
