version: '3.8'
services:
  app1:
    build:
      context: ./app
      args:
        app_port: ${APP_PORT}
    expose:
      - '${APP_PORT}' # Expose ports without publishing them to the host machine
    environment:
      MESSAGE: 'First instance'
      APP_PORT: ${APP_PORT}

  app2:
    build:
      context: ./app
      args:
        app_port: ${APP_PORT}
    expose:
      - '${APP_PORT}' # Expose ports without publishing them to the host machine
    environment:
      MESSAGE: 'Second instance'
      APP_PORT: ${APP_PORT}

  web:
    build:
      context: ./nginx
      args:
        app_port: ${APP_PORT}
    ports:
      - '${NGINX_EXTERNAL_PORT}:80'
    links:
      - app1
      - app2
